//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapsProjectApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapsProjectApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutMenuItemText {
            get {
                return ResourceManager.GetString("AboutMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed and published by Nokia. All rights reserved..
        /// </summary>
        public static string AboutPageCopyrightText {
            get {
                return ResourceManager.GetString("AboutPageCopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Explorer application is a Nokia Developer example demonstrating the use of the map component of Windows Phone 8..
        /// </summary>
        public static string AboutPageDescriptionText {
            get {
                return ResourceManager.GetString("AboutPageDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://projects.developer.nokia.com/mapexplorer.
        /// </summary>
        public static string AboutPageDeveloperUrl {
            get {
                return ResourceManager.GetString("AboutPageDeveloperUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more at .
        /// </summary>
        public static string AboutPageLearnMoreText {
            get {
                return ResourceManager.GetString("AboutPageLearnMoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string AboutPageVersionText {
            get {
                return ResourceManager.GetString("AboutPageVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP EXPLORER.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calculating route....
        /// </summary>
        public static string CalculatingRouteProgressText {
            get {
                return ResourceManager.GetString("CalculatingRouteProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dark color mode.
        /// </summary>
        public static string ColorModeDarkMenuItemText {
            get {
                return ResourceManager.GetString("ColorModeDarkMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light color mode.
        /// </summary>
        public static string ColorModeLightMenuItemText {
            get {
                return ResourceManager.GetString("ColorModeLightMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directions off.
        /// </summary>
        public static string DirectionsOffMenuItemText {
            get {
                return ResourceManager.GetString("DirectionsOffMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directions on.
        /// </summary>
        public static string DirectionsOnMenuItemText {
            get {
                return ResourceManager.GetString("DirectionsOnMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getting location....
        /// </summary>
        public static string GettingLocationProgressText {
            get {
                return ResourceManager.GetString("GettingLocationProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to landmarks off.
        /// </summary>
        public static string LandmarksOffMenuItemText {
            get {
                return ResourceManager.GetString("LandmarksOffMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to landmarks on.
        /// </summary>
        public static string LandmarksOnMenuItemText {
            get {
                return ResourceManager.GetString("LandmarksOnMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locate me.
        /// </summary>
        public static string LocateMeMenuButtonText {
            get {
                return ResourceManager.GetString("LocateMeMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is disabled in phone settings.
        /// </summary>
        public static string LocationDisabledMessageBoxText {
            get {
                return ResourceManager.GetString("LocationDisabledMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your location.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current location not available.
        /// </summary>
        public static string NoCurrentLocationMessageBoxText {
            get {
                return ResourceManager.GetString("NoCurrentLocationMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found. Narrow your search e.g. &quot;Seattle Wa&quot;.
        /// </summary>
        public static string NoMatchFoundMessageBoxText {
            get {
                return ResourceManager.GetString("NoMatchFoundMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pedestrian features off.
        /// </summary>
        public static string PedestrianFeaturesOffMenuItemText {
            get {
                return ResourceManager.GetString("PedestrianFeaturesOffMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pedestrian features on.
        /// </summary>
        public static string PedestrianFeaturesOnMenuItemText {
            get {
                return ResourceManager.GetString("PedestrianFeaturesOnMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route.
        /// </summary>
        public static string RouteMenuButtonText {
            get {
                return ResourceManager.GetString("RouteMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searching....
        /// </summary>
        public static string SearchingProgressText {
            get {
                return ResourceManager.GetString("SearchingProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchMenuButtonText {
            get {
                return ResourceManager.GetString("SearchMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsMenuButtonText {
            get {
                return ResourceManager.GetString("SettingsMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
    }
}
